### ISSUE TITLE
Any interest in packaging this for epel6?

### ISSUE THREAD

**Issue by ralphbean** [hughsie/python-appstream#1]
I'd be glad to do the work.. but is it something you'd want to be done?  (I don't see any other available appstream libs there).

**Comment by hughsie** [comment]
I created the project for old rhels like this, so no objection from me. Happy to do tarballs and have a spec file in git too if that helps.

**Comment by ralphbean** [comment]
OK, I'm going to upload it to pypi as well (to make development in a python virtualenv simple).

**Comment by hughsie** [comment]
Works for me, thanks. Yell if I'm doing anything anti-pythonic that breaks things.

**Comment by ralphbean** [comment]
Review up here:  https://bugzilla.redhat.com/show_bug.cgi?id=1275057
